# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pet.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'pet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tpet.proto\x12\x0bpetadoption\"N\n\x03Pet\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\r\n\x05\x62reed\x18\x04 \x01(\t\x12\r\n\x05photo\x18\x05 \x01(\x0c\".\n\rAddPetRequest\x12\x1d\n\x03pet\x18\x01 \x01(\x0b\x32\x10.petadoption.Pet\"\'\n\rGetPetRequest\x12\x16\n\x0e\x63haracteristic\x18\x01 \x01(\t\",\n\x0bPetResponse\x12\x1d\n\x03pet\x18\x01 \x01(\x0b\x32\x10.petadoption.Pet2\x8c\x01\n\nPetService\x12>\n\x06\x41\x64\x64Pet\x12\x1a.petadoption.AddPetRequest\x1a\x18.petadoption.PetResponse\x12>\n\x06GetPet\x12\x1a.petadoption.GetPetRequest\x1a\x18.petadoption.PetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PET']._serialized_start=26
  _globals['_PET']._serialized_end=104
  _globals['_ADDPETREQUEST']._serialized_start=106
  _globals['_ADDPETREQUEST']._serialized_end=152
  _globals['_GETPETREQUEST']._serialized_start=154
  _globals['_GETPETREQUEST']._serialized_end=193
  _globals['_PETRESPONSE']._serialized_start=195
  _globals['_PETRESPONSE']._serialized_end=239
  _globals['_PETSERVICE']._serialized_start=242
  _globals['_PETSERVICE']._serialized_end=382
# @@protoc_insertion_point(module_scope)
