# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pet_pb2 as pet__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PetServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddPet = channel.unary_unary(
                '/petadoption.PetService/AddPet',
                request_serializer=pet__pb2.AddPetRequest.SerializeToString,
                response_deserializer=pet__pb2.PetResponse.FromString,
                _registered_method=True)
        self.GetPet = channel.unary_unary(
                '/petadoption.PetService/GetPet',
                request_serializer=pet__pb2.GetPetRequest.SerializeToString,
                response_deserializer=pet__pb2.PetResponse.FromString,
                _registered_method=True)


class PetServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddPet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddPet': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPet,
                    request_deserializer=pet__pb2.AddPetRequest.FromString,
                    response_serializer=pet__pb2.PetResponse.SerializeToString,
            ),
            'GetPet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPet,
                    request_deserializer=pet__pb2.GetPetRequest.FromString,
                    response_serializer=pet__pb2.PetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'petadoption.PetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('petadoption.PetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PetService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddPet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/petadoption.PetService/AddPet',
            pet__pb2.AddPetRequest.SerializeToString,
            pet__pb2.PetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/petadoption.PetService/GetPet',
            pet__pb2.GetPetRequest.SerializeToString,
            pet__pb2.PetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
